/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.geektrust.learning;

import org.junit.Test;
import static org.junit.Assert.*;

public class GeektrustTest {
    @Test public void appHasAGreeting() {
        Geektrust classUnderTest = new Geektrust();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
